#######################################
## Environment Configuration
##  - feel free to edit -
## -> for most changes you only have to
##         docker-compose up -d
##    to apply them
########################################
#
########################################
## MySQL settings
## -> if you change these settings
##    you have to remove the database:
##         docker-compose rm mysql
##    because it's stored database in
##    volume and provisioning is only
##    done once.
MYSQL_ROOT_PASSWORD=xxxxxxxxxxxx
MYSQL_USER=stats
MYSQL_PASSWORD=stats
MYSQL_DATABASE=stats
#
